### ISSUE TITLE
Mobile friendly UI

### ISSUE THREAD

**Issue by mizzunet** [DBKarman/lyricsync#4]
Would you consider making the UI mobile screen friendly?

Thanks

**Comment by DBKarman** [comment]
Hi,

I will try to roll out a fix soon but it might take me anywhere from a week until Christmas, University is taking up all my time at the moment.

**Comment by DBKarman** [comment]
Hi, 

I managed to make it more mobile friendly and also made it so that progress wouldnt be lost if changing tabs.

Have a nice day,
DBKarman
